services:
  ocr:
    image: ocr
    build: .
    mem_limit: 6G
    mem_reservation: 6G
    tmpfs:
      - /tmp:size=100M
    volumes:
      - ${HOME}/data/input:/data/input:ro
      - ${HOME}/data/output:/data/output

