version: "3.9"
services:
  ocr:
    image: ocr
    build: .
    mem_limit: 6G
    mem_reservation: 6G
    tmpfs:
      - /tmp:size=100M
    volumes:
        - ~/data/input:/home/appuser/data/input:ro
        - ~/data/output:/home/appuser/data/output
    restart: always

#IMPORTANT: YOU NEED TO RUN THE DOCKER COMPOSE UP AS A NORMAL USER NOT SUPER USER
#otherwise the mount will not work

