services:
  ocr:
    image: ocr
    build: .
    mem_limit: 6G
    mem_reservation: 6G
    tmpfs:
      - /tmp:size=100M
    volumes:
      - ${HOME}/data/input:/home/appuser/data/input:ro
      - ${HOME}/data/output:/home/appuser/data/output

